// Drop-in replacement for `lucide-react-native` imports. Every icon is
// fetched from Iconify's lucide mirror (scripts/generate-icons.mjs) as a
// plain .svg asset and wrapped here to match lucide's component API (size,
// color, strokeWidth). Import from this module instead of the npm package;
// re-run the generator script and add an export here to bring in a new icon.
import AccessibilitySvg from "@/assets/icons/lucide/accessibility.svg";
import ArrowDownLeftSvg from "@/assets/icons/lucide/arrow-down-left.svg";
import ArrowDownRightSvg from "@/assets/icons/lucide/arrow-down-right.svg";
import ArrowRightSvg from "@/assets/icons/lucide/arrow-right.svg";
import ArrowUpRightSvg from "@/assets/icons/lucide/arrow-up-right.svg";
import BellSvg from "@/assets/icons/lucide/bell.svg";
import BusSvg from "@/assets/icons/lucide/bus.svg";
import CalendarClockSvg from "@/assets/icons/lucide/calendar-clock.svg";
import ChartPieSvg from "@/assets/icons/lucide/chart-pie.svg";
import CheckSvg from "@/assets/icons/lucide/check.svg";
import ChevronLeftSvg from "@/assets/icons/lucide/chevron-left.svg";
import ChevronRightSvg from "@/assets/icons/lucide/chevron-right.svg";
import CircleCheckSvg from "@/assets/icons/lucide/circle-check.svg";
import ClapperboardSvg from "@/assets/icons/lucide/clapperboard.svg";
import CoffeeSvg from "@/assets/icons/lucide/coffee.svg";
import CoinsSvg from "@/assets/icons/lucide/coins.svg";
import CreditCardSvg from "@/assets/icons/lucide/credit-card.svg";
import DeleteSvg from "@/assets/icons/lucide/delete.svg";
import DumbbellSvg from "@/assets/icons/lucide/dumbbell.svg";
import FlameSvg from "@/assets/icons/lucide/flame.svg";
import GraduationCapSvg from "@/assets/icons/lucide/graduation-cap.svg";
import HeartPulseSvg from "@/assets/icons/lucide/heart-pulse.svg";
import HouseSvg from "@/assets/icons/lucide/house.svg";
import LockSvg from "@/assets/icons/lucide/lock.svg";
import LogOutSvg from "@/assets/icons/lucide/log-out.svg";
import MoonSvg from "@/assets/icons/lucide/moon.svg";
import PiggyBankSvg from "@/assets/icons/lucide/piggy-bank.svg";
import PlusSvg from "@/assets/icons/lucide/plus.svg";
import RepeatSvg from "@/assets/icons/lucide/repeat.svg";
import RotateCcwSvg from "@/assets/icons/lucide/rotate-ccw.svg";
import SearchXSvg from "@/assets/icons/lucide/search-x.svg";
import ShoppingBagSvg from "@/assets/icons/lucide/shopping-bag.svg";
import SparklesSvg from "@/assets/icons/lucide/sparkles.svg";
import SunSvg from "@/assets/icons/lucide/sun.svg";
import SunMoonSvg from "@/assets/icons/lucide/sun-moon.svg";
import TargetSvg from "@/assets/icons/lucide/target.svg";
import TrendingDownSvg from "@/assets/icons/lucide/trending-down.svg";
import TrendingUpSvg from "@/assets/icons/lucide/trending-up.svg";
import TriangleAlertSvg from "@/assets/icons/lucide/triangle-alert.svg";
import TrophySvg from "@/assets/icons/lucide/trophy.svg";
import UserSvg from "@/assets/icons/lucide/user.svg";
import UtensilsSvg from "@/assets/icons/lucide/utensils.svg";
import VibrateSvg from "@/assets/icons/lucide/vibrate.svg";
import WalletSvg from "@/assets/icons/lucide/wallet.svg";
import WandSparklesSvg from "@/assets/icons/lucide/wand-sparkles.svg";
import XSvg from "@/assets/icons/lucide/x.svg";
import ZapSvg from "@/assets/icons/lucide/zap.svg";

import { createIcon, type IconComponent } from "./create-icon";

export type { IconComponent };

export const Accessibility = createIcon(AccessibilitySvg);
export const ArrowDownLeft = createIcon(ArrowDownLeftSvg);
export const ArrowDownRight = createIcon(ArrowDownRightSvg);
export const ArrowRight = createIcon(ArrowRightSvg);
export const ArrowUpRight = createIcon(ArrowUpRightSvg);
export const Bell = createIcon(BellSvg);
export const Bus = createIcon(BusSvg);
export const CalendarClock = createIcon(CalendarClockSvg);
export const ChartPie = createIcon(ChartPieSvg);
export const Check = createIcon(CheckSvg);
export const ChevronLeft = createIcon(ChevronLeftSvg);
export const ChevronRight = createIcon(ChevronRightSvg);
export const CheckCircle2 = createIcon(CircleCheckSvg);
export const Clapperboard = createIcon(ClapperboardSvg);
export const Coffee = createIcon(CoffeeSvg);
export const Coins = createIcon(CoinsSvg);
export const CreditCard = createIcon(CreditCardSvg);
export const Delete = createIcon(DeleteSvg);
export const Dumbbell = createIcon(DumbbellSvg);
export const Flame = createIcon(FlameSvg);
export const GraduationCap = createIcon(GraduationCapSvg);
export const HeartPulse = createIcon(HeartPulseSvg);
export const Home = createIcon(HouseSvg);
export const House = createIcon(HouseSvg);
export const Lock = createIcon(LockSvg);
export const LogOut = createIcon(LogOutSvg);
export const Moon = createIcon(MoonSvg);
export const PiggyBank = createIcon(PiggyBankSvg);
export const Plus = createIcon(PlusSvg);
export const Repeat = createIcon(RepeatSvg);
export const RotateCcw = createIcon(RotateCcwSvg);
export const SearchX = createIcon(SearchXSvg);
export const ShoppingBag = createIcon(ShoppingBagSvg);
export const Sparkles = createIcon(SparklesSvg);
export const Sun = createIcon(SunSvg);
export const SunMoon = createIcon(SunMoonSvg);
export const Target = createIcon(TargetSvg);
export const TrendingDown = createIcon(TrendingDownSvg);
export const TrendingUp = createIcon(TrendingUpSvg);
export const TriangleAlert = createIcon(TriangleAlertSvg);
export const AlertTriangle = createIcon(TriangleAlertSvg);
export const Trophy = createIcon(TrophySvg);
export const User = createIcon(UserSvg);
export const Utensils = createIcon(UtensilsSvg);
export const Vibrate = createIcon(VibrateSvg);
export const Wallet = createIcon(WalletSvg);
export const Wand2 = createIcon(WandSparklesSvg);
export const X = createIcon(XSvg);
export const Zap = createIcon(ZapSvg);
